### ISSUE TITLE
Create forms.py

### ISSUE THREAD

**Issue by varshaasj** [CMU-313/fall-2021-hw2-redfox#10] opened 2021-09-27 22:47 UTC

**Comment by yanmulin** [comment] 2021-09-30 13:57
This issue might be a duplicate of https://github.com/CMU-313/fall-2021-hw2-redfox/issues/7 if it is to implement `ModelForm` in `form.py`.

**Comment by epguthrie** [comment] 2021-10-02 00:53
Resolved in previous pulls, including #13 and #14.

**Closed as completed by epguthrie** 2021-10-02 00:53 UTC
Labels: frontend
